[package]
name = "ftlman"
version = "0.1.2"
edition = "2021"

[dependencies]
env_logger = "0.11"
log = "0.4"

eframe = { version = "0.27", features = ["persistence"] }
ureq = "2"
egui_dnd = "0.8.0"
dirs = "5"
anyhow = "1.0"
regex = "1"
lazy_static = "1"
once_cell = "1"

parking_lot = "0.12"
poll-promise = { version = "0.3" }

# Used to read/write SIL archives and mod files/dirs
silpkg = { git = "https://github.com/afishhh/silpkg.git" }
zip = "0.6.3"
walkdir = "2"

# Used in cache.rs
base32 = "0.4"
tempfile = "3"

# Used for persisting state and deserializing mod metadata
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.31", features = ["serialize"] }

# Used in append.rs
xmltree = "0.10"

# Speeds up testing considerably
[profile.dev]
opt-level = 2
