[package]
name = "ftlman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
log = "0.4"

eframe = { version = "0.25", features = ["persistence"] }
ureq = "2"
egui_dnd = "0.6.0"
xdg = "2"
anyhow = "1.0"
regex = "1"
lazy_static = "1"
once_cell = "1"

parking_lot = "0.12"
poll-promise = { version = "0.3" }

# version = "12" deoesn't build without async...
cacache = { version = "11", features = ["mmap"], default-features = false }

silpkg = { git = "https://github.com/afishhh/silpkg.git" }
walkdir = "2"
zip = "0.6.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.31", features = ["serialize"] }
xmltree = "0.10"

# Speeds up testing considerably
[profile.dev]
opt-level = 3
