[package]
name = "ftlman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
log = "0.4"

eframe = { version = "0.25", features = ["persistence"] }
egui_dnd = "0.6.0"
xdg = "2.4"
anyhow = "1.0"
regex = "1.7"
lazy_static = "1.4"
once_cell = "1.19"

# This could be removed
natord = "1.0"

tokio = { version = "1.23", features = ["full", "macros"] }
tokio-stream = "0.1"
poll-promise = { version = "0.3", features = ["tokio"] }

reqwest = { version = "0.11", features = ["stream", "json"] }
cacache = "12"
ssri = "9"

silpkg = { path = "../silpkg" }
walkdir = "2.3"
zip = "0.6.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.29", features = ["serialize", "async-tokio"] }
xmltree = "0.10"
