[package]
name = "ftlman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11"
log = "0.4"

eframe = { version = "0.25", features = ["persistence"] }
ureq = "2"
egui_dnd = "0.6.0"
xdg = "2.4"
anyhow = "1.0"
regex = "1.7"
lazy_static = "1.4"
once_cell = "1.19"

parking_lot = "0.12"
poll-promise = { version = "0.3" }

# version = "12" deoesn't build without async...
cacache = { version = "11", features = ["mmap"], default-features = false }

silpkg = { git = "https://github.com/afishhh/silpkg.git" }
walkdir = "2.3"
zip = "0.6.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = { version = "0.31", features = ["serialize", "async-tokio"] }
xmltree = "0.10"

# Somewhat speeds up testing with debug builds
[profile.dev.package.xml-rs]
opt-level = 3
